// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DownloadCsvTemplate(arg1) {
  return window['go']['main']['App']['DownloadCsvTemplate'](arg1);
}

export function DownloadImage2Text(arg1, arg2) {
  return window['go']['main']['App']['DownloadImage2Text'](arg1, arg2);
}

export function GetDirs(arg1) {
  return window['go']['main']['App']['GetDirs'](arg1);
}

export function Greet(arg1, arg2) {
  return window['go']['main']['App']['Greet'](arg1, arg2);
}

export function Image2Text(arg1) {
  return window['go']['main']['App']['Image2Text'](arg1);
}

export function LLM(arg1, arg2) {
  return window['go']['main']['App']['LLM'](arg1, arg2);
}

export function OpenFile(arg1) {
  return window['go']['main']['App']['OpenFile'](arg1);
}

export function OpenFolder(arg1, arg2) {
  return window['go']['main']['App']['OpenFolder'](arg1, arg2);
}

export function ParsePromptFile(arg1) {
  return window['go']['main']['App']['ParsePromptFile'](arg1);
}

export function ParseVisFile(arg1) {
  return window['go']['main']['App']['ParseVisFile'](arg1);
}

export function Replace(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['Replace'](arg1, arg2, arg3, arg4);
}

export function UploadImage(arg1) {
  return window['go']['main']['App']['UploadImage'](arg1);
}
