// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Config():Promise<{[key: string]: any}>;

export function DownloadCsvTemplate(arg1:string):Promise<{[key: string]: any}>;

export function DownloadImage2Text(arg1:string,arg2:string):Promise<{[key: string]: any}>;

export function GetDirs(arg1:string):Promise<{[key: string]: any}>;

export function Greet(arg1:string,arg2:string):Promise<string>;

export function Image2Text(arg1:string):Promise<void>;

export function LLM(arg1:string,arg2:string,arg3:string):Promise<void>;

export function OpenFile(arg1:string):Promise<{[key: string]: any}>;

export function OpenFolder(arg1:string,arg2:string):Promise<{[key: string]: any}>;

export function ParsePromptFile(arg1:string):Promise<{[key: string]: any}>;

export function Replace(arg1:string,arg2:string,arg3:Array<{[key: string]: string}>,arg4:Array<string>):Promise<{[key: string]: any}>;

export function SetUser(arg1:string,arg2:string,arg3:string):Promise<{[key: string]: any}>;

export function UploadImage(arg1:string):Promise<{[key: string]: any}>;
